# Generated by Django 2.1.2 on 2018-10-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyKeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('frequency', models.IntegerField()),
                ('description', models.CharField(max_length=2000)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
