# Generated by Django 2.1.2 on 2018-10-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64)),
                ('Mgt_IP', models.GenericIPAddressField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iName', models.CharField(max_length=64)),
                ('iType', models.IntegerField()),
                ('iIP', models.GenericIPAddressField()),
                ('description', models.CharField(max_length=200)),
                ('iVlan', models.CharField(max_length=64)),
            ],
        ),
    ]
