# Generated by Django 2.1.2 on 2018-11-05 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64)),
                ('Mgt_IP', models.GenericIPAddressField(null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('device_type', models.CharField(max_length=64, null=True)),
                ('version', models.CharField(max_length=10, null=True)),
                ('running_configure', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iName', models.CharField(max_length=64)),
                ('iType', models.IntegerField(null=True)),
                ('iIP', models.GenericIPAddressField(null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('iVlan', models.CharField(max_length=64, null=True)),
                ('iUsed', models.BooleanField(null=True)),
                ('iDevice', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='network.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('frequncy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='label',
            name='person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='network.Person'),
        ),
        migrations.AddField(
            model_name='activity',
            name='label',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='network.Label'),
        ),
        migrations.AddField(
            model_name='activity',
            name='person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='network.Person'),
        ),
    ]
