# Generated by Django 2.1.2 on 2018-10-26 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='iDevice',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='network.Device'),
        ),
    ]
