# Generated by Django 2.1.2 on 2018-11-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20181107_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='remote_device_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='remote_interface_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
