# Generated by Django 2.1.2 on 2018-10-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_interface_idevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='iUsed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='Mgt_IP',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='iIP',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='iType',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='iVlan',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
